#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########

set +x
set -e

#############################
# Place end code here

sudo rm -R /home/pi/temp