#!/usr/bin/env bash
# TOUCHSCREEN for CommunityOS
# Selects and installs touchscreen drivers for CommunityOS
# Written by <author>
# GPL V3
########

##############################
### Source error handling, leave this in place

set +x
set -e

export LC_ALL=C

source /common.sh
install_cleanup_trap

##############################
### Add required driver code here


##############################
### Clean up before exiting

apt-get clean
apt-get autoremove -y
set -x