#!/usr/bin/env bash
# Plugins for CommunityOS
# Sets up CommunityOS OctoPrint Plugins
# Written by Bud Hammerton
# GPL V3
########

##############################
### Source error handling, leave this in place

set +x
set -e

export LC_ALL=C

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

##############################
### Put plugin code here

##############################
### Clean up before exiting

apt-get clean
apt-get autoremove -y
set -x