webcam:
  stream: /webcam/?action=stream
  snapshot: http://127.0.0.1:8080/?action=snapshot
  ffmpeg: /usr/bin/avconv
  watermark: false
plugins:
  cura:
    cura_engine: /usr/local/bin/cura_engine
  discovery:
    publicPort: 80
server:
  commands:
    systemShutdownCommand: sudo shutdown -h now
    systemRestartCommand: sudo shutdown -r now
    serverRestartCommand: sudo service octoprint restart
  onlineCheck:
    enabled: true
  pluginBlacklist:
    enabled: true
serial:
  baudrate: 250000
  log: false
  maxCommunicationTimeouts: {}
  port: /dev/ttyACM0
  timeout:
    communication: 120.0
temperature:
  profiles:
  - bed: '80'
    extruder: '240'
    name: ABS
  - bed: '45'
    extruder: '200'
    name: PLA
  - bed: '65'
    extruder: '230'
    name: PETG
printerProfiles:
  default: _default
appearance:
  color: blue
  name: "Robo3D"
feature:
  keyboardControl: false
  