#!/usr/bin/env bash
# Touchscreen UI for CommunityOS
# Selects and installs enabled touchscreen for CommunityOS
# Written by <Author>
# GPL V3
########

set -x
set -e

cd /home/pi
if [ -e "/home/pi/octoprint-tft_stretch*" ]
then
  sudo rm -R /home/pi/octoprint-tft_stretch*
fi